### ISSUE TITLE
Broken link on the ZoneMinder Wiki

### ISSUE THREAD

**Issue by Derek-Strasters** [pliablepixels/zmhacks#1]
Hello and thank you for your work,
    There is a broken link to https://github.com/pliablepixels/zmhacks/blob/master/zmpkg.pl on the zoneminder wiki page at https://wiki.zoneminder.com/Modifying_ZoneMinder_to_remember_run_state_names as well as some instructions that are deprecated as per what you have written in your README file about the **isActive** method being built in.

I'm actually not sure who maintains the Wiki so I apologize if I'm in error contacting you, I thought this would be a good place to start though.

Cheers,
    -Derek

**Comment by Derek-Strasters** [comment]
It also appears the **console.php** is no longer in the repo.

**Comment by pliablepixels** [comment]
Thanks - I added a deprecation notice to that wiki entry.
I added this feature to ZM directly, so it now remembers run states
inherently. So no additional mods needed.
